export const GENISIS_NFT_ADDRESSES = {
  goerli: "",
  sepolia: "0x78aE61943989789C7eBD58d868E5c7cb77684473",
  hardhat: "",
  kovan: "",
  mainnet: "",
  rinkeby: "",
  ropsten: "",
  bsc: "",
  bsctest: "",
  xinfin: "",
  apothem: "",
  polygon: "",
  mumbai: "",
  scrollSepolia: "",
};

export const GENESIS_NFT_DATA_ADDRESSES = {
  goerli: "",
  sepolia: "0x24f21A41b4BA35eaF310ff3710800960BB715AE4",
  hardhat: "",
  kovan: "",
  mainnet: "",
  rinkeby: "",
  ropsten: "",
  bsc: "",
  bsctest: "",
  xinfin: "",
  apothem: "",
  polygon: "",
  mumbai: "",
  scrollSepolia: "",
};

export const GENESIS_NFT_ATTRIBUTES_ADDRESSES = {
  goerli: "",
  sepolia: "0x05394b2A6B62E8b8A327d3e4a585823423EBe624",
  hardhat: "",
  kovan: "",
  mainnet: "",
  rinkeby: "",
  ropsten: "",
  bsc: "",
  bsctest: "",
  xinfin: "",
  apothem: "",
  polygon: "",
  mumbai: "",
  scrollSepolia: "",
};
