export const GENISIS_NFT_ADDRESSES = {
  goerli: "",
  sepolia: "0x308a770Ce2E3627F791918BB5580e683A6F4DEAf",
  hardhat: "",
  kovan: "",
  mainnet: "",
  rinkeby: "",
  ropsten: "",
  bsc: "",
  bsctest: "",
  xinfin: "",
  apothem: "",
  polygon: "",
  mumbai: "",
  scrollSepolia: "",
};

export const GENESIS_NFT_DATA_ADDRESSES = {
  goerli: "",
  sepolia: "0x0DDfeEf23156fd69b920c74ca1Efa6bbD856e324",
  hardhat: "",
  kovan: "",
  mainnet: "",
  rinkeby: "",
  ropsten: "",
  bsc: "",
  bsctest: "",
  xinfin: "",
  apothem: "",
  polygon: "",
  mumbai: "",
  scrollSepolia: "",
};

export const GENESIS_NFT_ATTRIBUTES_ADDRESSES = {
  goerli: "",
  sepolia: "0x4D0468a2368736891E0E09fE1cf409Af6A1bD76f",
  hardhat: "",
  kovan: "",
  mainnet: "",
  rinkeby: "",
  ropsten: "",
  bsc: "",
  bsctest: "",
  xinfin: "",
  apothem: "",
  polygon: "",
  mumbai: "",
  scrollSepolia: "",
};
