export const REWARD_SHARES_ADDRESSES = {
  goerli: "",
  sepolia: "0x6A73c40B0bc50232d2215e854D73Ed32713f0EF6",
  hardhat: "",
  kovan: "",
  mainnet: "",
  rinkeby: "",
  ropsten: "",
  bsc: "",
  bsctest: "",
  xinfin: "",
  apothem: "",
  polygon: "",
  mumbai: "",
  scrollSepolia: "",
};

export const REWARD_TOKENS_ADDRESSES = {
  goerli: "",
  sepolia: "0xe575B1B5a8685B74324833116e427A75770b856E",
  hardhat: "",
  kovan: "",
  mainnet: "",
  rinkeby: "",
  ropsten: "",
  bsc: "",
  bsctest: "",
  xinfin: "",
  apothem: "",
  polygon: "",
  mumbai: "",
  scrollSepolia: "",
};

export const REWARD_WRAPPER_ADDRESSES = {
  goerli: "",
  sepolia: "0xff802ED8d4D51B70e373Ea5eE38c16185dd6E657",
  hardhat: "",
  kovan: "",
  mainnet: "",
  rinkeby: "",
  ropsten: "",
  bsc: "",
  bsctest: "",
  xinfin: "",
  apothem: "",
  polygon: "",
  mumbai: "",
  scrollSepolia: "",
};
